### ISSUE TITLE
[Problem] UX: Getting back from Blog to Start page

### ISSUE THREAD

**Issue by hkienle** [Ondsel-Development/FreeCAD#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In the Start page one can click on the "Blog" link. Once there, it is not intuitive how to get back to the Start page again. Doing a right-click and selecting Back is the only way I know.

Once you get back, all images are broken. You have to do a right-click and Reload to fix this.

![image](https://github.com/Ondsel-Development/FreeCAD/assets/17142458/6cf39cce-46f5-419d-9f6b-e30c650c9e0c)

FreeCAD has the same issue, I just thought Ondsel would perhaps care more about things like this. ;)

### Full version info

```shell
OS: PureOS 10 (Byzantium) (GNOME/gnome-xorg)
Word size of Ondsel: 64-bit
Version: 2024.1.0.35631 (Git) AppImage
Build type: Release
Branch: flavor
Hash: badd90ef6d13904890e30a8d8170c8620c7e5a76
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * OpenDark 2023.12.17
  * Ondsel-Lens 2024.1.22.01
```
```


### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
Due to all the unnecessary complications related to running a webpage inside the app the start page has been rewritten in the latest release and no longer has a blog link
