### ISSUE TITLE
In downloads of weekly builds, links to aarch64 and x86_64 are swapped

### ISSUE THREAD

**Issue by kopchik** [Ondsel-Development/FreeCAD#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hi! The links are swapped in download area (https://lens.ondsel.com/download-and-explore): when clicking "download x86_64 Image" it downloads image for aarch64 and vice versa:

![image](https://github.com/user-attachments/assets/5bbf13b7-2f74-4297-bc16-19da163da749)

### Full version info

```shell
OS: NixOS 24.05 (Uakari) (GNOME/gnome)
Word size of Ondsel: 64-bit
Version: 2024.3.0dev.38774 (Git)
Build type: Release
Branch: flavor
Hash: ffe317963d6ddb51fc4d1aacc639b1a69fbb2241
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Qt default
Installed mods: 
  * Ondsel-Lens 2024.7.5.02
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prokoudine** [comment]
Should be fixed now
