### ISSUE TITLE
4k display support

### ISSUE THREAD

**Issue by InfernalWolf666** [Ondsel-Development/FreeCAD#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When setting the dimensions of the part, it is impossible to see the numbers

### Full version info

```shell
news
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by InfernalWolf666** [comment]
When setting the dimensions of the part, it is impossible to see the numbers

**Comment by prokoudine** [comment]
Hi, Ondsel is [shutting down](https://ondsel.com/blog/goodbye/), so there will be no further development of Ondsel ES. We recommend using FreeCAD 1.0. It has 99.5% of our patches, and you can easily [make it look like Ondsel ES](https://librearts.org/2024/11/freecad-to-ondsel-es-look/).

**Comment by InfernalWolf666** [comment]
It's a pity, you had an interesting style.
