### ISSUE TITLE
[Problem] Windows Extraction of `Ondsel` Fail

### ISSUE THREAD

**Issue by DieSwartKat** [Ondsel-Development/FreeCAD#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I downloaded the 7z file (windows version) from Ondsel's website to extract it. 

![image](https://github.com/Ondsel-Development/FreeCAD/assets/49644543/25223e3f-bbfa-48f0-875f-c20b33f323d1)

I get this error during extraction:
```
! ...\ondsel\Ondsel_ES_2024.1.0.35694-Windows-x86_64.7z: Unknown method in Ondsel_ES_2024.1.0.35694-Windows-x86_64\bin\Lib\site-packages\pip\_vendor\distlib\t64-arm.exe
! ...\ondsel\Ondsel_ES_2024.1.0.35694-Windows-x86_64.7z: Unknown method in Ondsel_ES_2024.1.0.35694-Windows-x86_64\bin\Lib\site-packages\pip\_vendor\distlib\w64-arm.exe
! ...\ondsel\Ondsel_ES_2024.1.0.35694-Windows-x86_64.7z: Unknown method in Ondsel_ES_2024.1.0.35694-Windows-x86_64\bin\Lib\site-packages\setuptools\cli-arm64.exe
! ...\ondsel\Ondsel_ES_2024.1.0.35694-Windows-x86_64.7z: Unknown method in Ondsel_ES_2024.1.0.35694-Windows-x86_64\bin\Lib\site-packages\setuptools\gui-arm64.exe
```

I'm not sure if this is the correct place to report this, but since the link on the website points to this repo I figure someone here will care. I've also emailed ondsel, but had no response.

Let me know if you need any help.

### Full version info

```shell
Ondsel_ES_2024.1.0.35694-Windows-x86_64.7z
```

### Subproject(s) affected?

Other (specify in description)

### Anything else?

https://github.com/Ondsel-Development/FreeCAD/releases/download/2024.1.0/Ondsel_ES_2024.1.0.35694-Windows-x86_64.7z

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
this should be solved by now
