### ISSUE TITLE
[Problem] No Windows installer, no installation instructions

### ISSUE THREAD

**Issue by 30350n** [Ondsel-Development/FreeCAD#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

While I personally like being able to download a portable build, the average user would probably prefer a simple installer. There's also no installation instructions whatsoever and I basically had to guess that I'd have to start the `freecad.exe`. Adding a simple README to the archive should fix this.

### Full version info

```shell
-
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prokoudine** [comment]
There is no installer yet because Ondsel is in the extended valication process to get a token to sign installers. This usually takes weeks.

**Comment by 30350n** [comment]
Ah okay, that makes sense, some additional guidance on how to use the current portable builds, probably wouldn't hurt still.

**Comment by jdressu** [comment]
Not entirely related but what are your plans for the "packages" you intend on making available?

Cus, (don't wanna be the odd one out.. and opinions are a dime a dozen.. but..) i on the other hand prefer to have the zipped package..

And just noticed the latest 'pre-release' only has the 'installer' package.. 😢

![image](https://github.com/Ondsel-Development/FreeCAD/assets/2261130/27572bae-41c0-4521-8c66-f579bff6c7b5)

**Comment by jdressu** [comment]
> Ah okay, that makes sense, some additional guidance on how to use the current portable builds, probably wouldn't hurt still.

Just noticed that there is guidance on the 'Support' page: https://ondsel.com/support/
(Not sure if it was there before. Probably was.)

![image](https://github.com/Ondsel-Development/FreeCAD/assets/2261130/08938f89-303b-4172-8ea1-092ca5290970)

**Comment by jdressu** [comment]
> Not entirely related but what are your plans for the "packages" you intend on making available?
> 
> Cus, (don't wanna be the odd one out.. and opinions are a dime a dozen.. but..) i on the other hand prefer to have the zipped package..
> 
> And just noticed the latest 'pre-release' only has the 'installer' package.. 😢
> 
> ![image](https://private-user-images.githubusercontent.com/2261130/328869101-27572bae-41c0-4521-8c66-f579bff6c7b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDUyMTAsIm5iZiI6MTcxNTI0NDkxMCwicGF0aCI6Ii8yMjYxMTMwLzMyODg2OTEwMS0yNzU3MmJhZS00MWMwLTQ1MjEtOGM2Ni1mNTc5YmZmNmM3YjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDlUMDg1NTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTBkMzk2NDc0YWJiNjc5ZTM3MWI0NWEwNDAxYjIwYWZkYmZiNDFiMmQwMTIzMWIxMDcwMjMwMDdmZjI2ZDQ3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qiTd4KjzXt8qYd0msKsR79xcDvTAMr2Wj68VJTEpNVc)

Ignore my comments, sorry for the "input noise" on the issue.
I simply downloaded the installer file and used 7zip to extract the files from inside of it. 👍

**Comment by prokoudine** [comment]
I'll close it then :)
