### ISSUE TITLE
[Problem]  Force Appimage to use KDE Native Dialog

### ISSUE THREAD

**Issue by ShiroyukiX** [Ondsel-Development/FreeCAD#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Is there a way to force the appimage to use the KDE native dialogue? The one built-in makes accessing my external drive cumbersome. Changing the `DontUseNativeDialog` parameter as `false` does nothing.

Preferably, I would build the program over using appimage but that doesn't appear to works from my experience.

### Full version info

```shell
OS: Arch Linux (KDE/plasma)
Word size of Ondsel: 64-bit
Version: 2024.1.0.35694 (Git) AppImage
Build type: Release
Branch: flavor
Hash: b070090c6873b3fcf4be9a459219d22edfc4e7cf
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.5.12
```
```


### Subproject(s) affected?

None

### Anything else?

https://wiki.freecad.org/Fine-tuning

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hkienle** [comment]
I think I ran into this problem a while ago as well with plain FreeCAD, so I think the issue is probably inherited from FreeCAD.
