### ISSUE TITLE
[Problem] Tree Covers Spreadsheet Cells

### ISSUE THREAD

**Issue by ahcox** [Ondsel-Development/FreeCAD#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![image](https://github.com/Ondsel-Development/FreeCAD/assets/1584013/2d843ed9-08c2-4ce2-9328-b790c1bd0b8b)
The  Model Tree / Object Tree covers up spreadsheet cells. Tiling the windows if there is a simple part design window and one spreadsheet open puts the spreadsheet on the left under the tree.

### Full version info

```shell
OS: Ubuntu 23.10 (ubuntu:GNOME/ubuntu)
Word size of Ondsel: 64-bit
Version: 2024.1.0.35694 (Git) AppImage
Build type: Release
Branch: flavor
Hash: b070090c6873b3fcf4be9a459219d22edfc4e7cf
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * OpenDark 2023.12.17
  * Ondsel-Lens 2024.1.22.01
```
```


### Subproject(s) affected?

Spreadsheet

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JohnOCFII** [comment]
Yes, I've seen that over the past few weeklies as well.  If I move my mouse to the right, the spreadsheet (properly) becomes the front "window" and the tree is hidden.

```
OS: macOS 14.4
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36526 (Git)
Build type: Release
Branch: main
Hash: 2ebbd83268ffabf41ceaad802714a4ffd9214437
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * OpenLight_Beta 2023.12.17
  * FeedsAndSpeeds 0.5.0
  * OpenDark 2023.12.17
```

<img width="1520" alt="Screenshot 2024-03-24 at 7 15 21 PM" src="https://github.com/Ondsel-Development/FreeCAD/assets/7844212/bd58e708-a90d-4645-8c21-5e7a8679155d">

**Comment by kinghat** [comment]
my tree is auto-hiding. if i run my mouse over to the edge the tree expands properly:

![image](https://github.com/Ondsel-Development/FreeCAD/assets/16073360/7c033d74-b7dd-4fdc-8936-bc8c8b72e3d5)

![image](https://github.com/Ondsel-Development/FreeCAD/assets/16073360/789b0cf2-25ec-4af8-b6a3-c43353f6ca87)

```
OS: Fedora Linux 39 (KDE Plasma) (KDE/plasma)
Word size of Ondsel: 64-bit
Version: 2024.2.0dev.36532 (Git) AppImage
Build type: Release
Branch: flavor
Hash: ab2d6d4dee83f717c7e9ac68b89e620cfa26b974
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * OpenDark 2023.12.17
  * Ondsel-Lens 2024.1.22.01
  * CurvedShapes 1.0.8
  * Curves 0.6.29
  * sheetmetal 0.4.6
  * fasteners 0.5.15
  * DynamicData 2.60.0
  * freecad.gears 1.2.0
  * lattice2 1.0.0
  * IconThemes
```

**Comment by JohnOCFII** [comment]
> my tree is auto-hiding. if i run my mouse over to the edge the tree expands properly:

Mine hides and unhides correctly AFTER the first initial display after I choose the spreadsheet (usually from the tab at the bottom of the window).  It is just the first time the spreadsheet shows up that the tree is still visible on top.
