### ISSUE TITLE
[Problem] The Default Colour Scheme Makes Spreadsheet Cells With Aliases Illegible in Dark Mode

### ISSUE THREAD

**Issue by ahcox** [Ondsel-Development/FreeCAD#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

![Screenshot from 2024-03-15 18-44-00](https://github.com/Ondsel-Development/FreeCAD/assets/1584013/73a53830-72a3-44b8-b231-e61924d8788d)

White text on a yellow background is very hard to read.

### Full version info

```shell
OS: Ubuntu 23.10 (ubuntu:GNOME/ubuntu)
Word size of Ondsel: 64-bit
Version: 2024.1.0.35694 (Git) AppImage
Build type: Release
Branch: flavor
Hash: b070090c6873b3fcf4be9a459219d22edfc4e7cf
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * OpenDark 2023.12.17
  * Ondsel-Lens 2024.1.22.01
```
```


### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prokoudine** [comment]
Thank you, this is an OpenDark issue, we'll see if we need to update to the latest version for a fix.
