### ISSUE TITLE
Expression Editor Window out of screen

### ISSUE THREAD

**Issue by Frenzel** [Ondsel-Development/FreeCAD#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Problem is simple. If you open the expression editor with an input box that is on the right side of the screen then the alignment of the box stays on the right side of that inputbox button, which is (mostly) off screen. And especially with smaller screens and more complex formula's this is problematic that every time you need to move this window and resize it.
![image](https://github.com/Ondsel-Development/FreeCAD/assets/221854/cd791b72-c5a5-4244-82fe-6a0139cf39ee)

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods: 
  * Curves 0.6.29
  * sheetmetal 0.2.63
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prokoudine** [comment]
Interestingly, I can confirm that on Windows 10, but not on Linux (Ubuntu 23.10)
