### ISSUE TITLE
Seams on cylinders and other curves are not removed/hidden with the "Refine" setting

### ISSUE THREAD

**Issue by raindropsfromsky** [Ondsel-Development/FreeCAD#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I get a seam on many parts.
The simplest case can be produced with these steps:
1. Draw a circle
2. Pad it
3. Select the top face and chamfer it

We get a seam on the cylindrical face and also on the chamfer.
![image](https://github.com/Ondsel-Development/FreeCAD/assets/9047168/bf868019-35ab-4075-82ec-2994c12f5440)

Note that the "Refine" parameter is set to true, but it is unable to remove the seam.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of Ondsel: 64-bit
Version: 2024.2.0dev.37608 (Git)
Build type: Release
Branch: flavor
Hash: cbb758c5dc79fd4c016a9cd45a007d3c7ce1a689
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/India (en_IN)
Installed mods: 
  * 3DfindIT 1.2.0
  * Ondsel-Lens 2024.3.26.01
  * SearchBar 1.0.2
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sliptonic** [comment]
This is correct behavior for the flat lines display mode.  Setting the display mode to 'shaded' will show the part without seams.
