### ISSUE TITLE
[1.0 bughunt] If we select the "points" draw style, the 3D object disappears in Parts Design WB

### ISSUE THREAD

**Issue by raindropsfromsky** [Ondsel-Development/FreeCAD#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In the Part Design WB, when we select the points draw style (v,2), the 3D object disappears!

To replicate this-
1. In PD WB, create a sketch.
2. Draw a sketch in the Sketcher WB (e.g. a rectangle) and close it.
3. Back in the PD WB, pad the sketch. We get a solid shape.
4. Press V,2 (or select the **_View > Draw style > Points_** menu)

**Expected behavior:**
All vertices of the 3D shape should be displayed.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of Ondsel: 64-bit
Version: 2024.2.1.37226 (Git)
Build type: Release
Branch: (HEAD detached at 2024.2.1)
Hash: 1a1bd7290494aef925a026c87b808ac58d53c3b0
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/India (en_IN)
Installed mods: 
  * 3DfindIT 1.2.0
  * Ondsel-Lens 2024.3.26.01
  * SearchBar 1.0.2
```

### Subproject(s) affected?

None

### Anything else?

See also bug #91

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sliptonic** [comment]
It doesn't entirely disappear.  The points view mode will only show the vertices.  So faces and edges are suppressed.
Behavior is by design.
