### ISSUE TITLE
The Help>About menu shows license for FreeCAD, not Ondsel 

### ISSUE THREAD

**Issue by raindropsfromsky** [Ondsel-Development/FreeCAD#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If we check out the license for Ondsel using the **Help > About Ondsel ES** menu, it shows the license for FREECAD, and not for Ondsel.

**Desired solution:**

Any one of the following:
1. Replace the word "FreeCAD" with "Ondsel ES" everywhere in the text, or 
2. Insert an introductory statement: "_the FreeCAD license is valid for Ondsel ES also_".

### Full version info

```shell
OS: Windows 11 build 22631
Word size of Ondsel: 64-bit
Version: 2024.2.0dev.37608 (Git)
Build type: Release
Branch: flavor
Hash: cbb758c5dc79fd4c016a9cd45a007d3c7ce1a689
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/India (en_IN)
Installed mods: 
  * 3DfindIT 1.2.0
  * fasteners 0.5.24
  * Ondsel-Lens 2024.3.26.01
  * PieMenu 1.7.0
  * SearchBar 1.0.2
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
should be fixed in our next release:
https://github.com/Ondsel-Development/FreeCAD/commit/07ea16501a0c8c049fcacd00009fd422059f58ad
